[package]
name = "restd"
version = "0.1.2"
edition = "2021"

description = "A re-implementation of various std features"
authors = ["Kyllingene"]
license = "MIT"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
